Fixing bugs with cards
Cattharine/product_owner_rl pull request #23
Opened 2023-12-28 17:32 UTC by Cattharine

+ userstory cards shouldn't be movable after moving one userstory card in the beginning of the game
 + one shouldn't be able to add any card to one place twice

2023-12-29 06:57 UTC, krutovsky-danya requested changes

2023-12-29 06:57 UTC, krutovsky-danya commented on game/game.py
> +            if not card.is_in_release:
Это же and

2023-12-29 06:57 UTC, krutovsky-danya commented on game/game.py
> +            if card.is_in_release:
И elif-ами можно пользоваться)

2023-12-29 06:57 UTC, krutovsky-danya commented on test/test_game_functions.py
> +        card = Card()
Не равнозначные названия, тога нужно card1

2024-01-01 09:28 UTC, krutovsky-danya requested changes

2024-01-01 09:28 UTC, krutovsky-danya commented on game/game.py
> +        elif not card.is_in_release:
Тут правда теперь условия не то. Раньше было `if not is_on_left and not card.is_in_release`, а теперь через или

2024-01-04 18:43 UTC, krutovsky-danya approved these changes

2024-01-04 18:43 UTC, krutovsky-danya commented on game/backlog/backlog.py
> +        return hours_to_sum != 0 or self.context.customers > 0 or self.context.customers < 0
Все хорошо, только это выгладит странно
Можно заменить на abs(...) > 0 или оставить != 0

2024-01-05 20:17 UTC, krutovsky-danya requested changes
Сорри, еще докопаюсь:
В наградах за действия нет проверки, что карточку можно двигать и появляется положительная награда за не валидное действие. Так алгоритм застрянет в этом действии

2024-01-05 20:17 UTC, krutovsky-danya commented on environment/environment.py
> -            context.current_sprint_hours,
А давай еще и эту строку оставим)

2024-01-06 03:41 UTC, Cattharine commented on environment/environment.py
> -            context.current_sprint_hours,
С первым (про перенос карточки) согласна, такое изменение я вносила, но оно потерялось при переносе. Внесла изменение
Для второго (оставлять строку с `context.current_sprint_hours`) я пока что-то не вижу причин. Пояснишь?

2024-01-06 09:51 UTC, krutovsky-danya commented on environment/environment.py
> -            context.current_sprint_hours,
Просто из соображения больше информации - лучше
Если дать ей оба кусочка данных, она легко сможет понять, что роботы будут работать и потратят деньги
Раньше сети приходилось самой складывать часы, чтобы не получить штраф за действие, а сейчас не придется, тем самым ускорится обучение
Если дать ей оба кусочка данных, она легко сможет понять, что роботы будут работать и потратят деньги
(Понял, что из-за лишнего добавления карточек в сеть, она не может посчитать сумму, нужно будет либо переделать, либо понять, что это не мешает)

2024-01-06 19:17 UTC, krutovsky-danya approved these changes

2024-01-15 08:26 UTC, merged