First semester research transfer
Cattharine/product_owner_rl pull request #27
Opened 2024-02-20 10:09 UTC by Cattharine

Add userstory environment
Add ability to choose whether you want agent to move sprint cards or not
Add or update environments for different stages in game
Update pipeline
Some minor updates
Typo fixes

2024-02-24 09:21 UTC, krutovsky-danya requested changes
Если что-то не хочется менять, давай заводить issue с запросом на изменения

2024-02-24 09:21 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +            nn.Linear(self.inner_layer, self.inner_layer),
Почему захотелось добавить еще слой? Тем более такой большой?
Может пока уберем эти изменения, а потом уже проверим, что изменения хорошие?

2024-02-24 09:21 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +                torch.tensor(action, dtype=torch.long),
Почему именно long?

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/__init__.py
> +from environment.stochastic_game_start_env import StochasticGameStartEnv
Здесь для единообразия тогда можно .stochastic_game_start_env поставить?

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/backlog_env.py
> +        self.with_sprint = True
Я смотрю на новое поле и не могу понять о чем оно, нужно выбрать другое название)

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
Я правильно понял, что это просто вырезает представление карточек спринта?
Кажется этот код тогда не нужен, можно же просто поставить ноль в нужное место, тогда из не будет представлять

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +        self.purchase_actions = {3, 4, 5, 6}
Это можно вынести из класса

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +        end_sprint = USUAL_CREDIT_ENV_END_SPRINT if self.with_end else EARLY_CREDIT_ENV_END_SPRINT
Это можно в конструкторе вычислить же

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +        self.with_end = with_end
На всякий случай тоже скажу, что название не очень говорящее

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +        reward = difference * 3
Волшебная константа, нужны пояснения откуда она взялась

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +            return -100
Сейчас может быть рановато, но давай в будущем использовать размер награды в рамках [-1; 1] по двум причинам:
1. Нейронки не очень любят резких скачков в значениях (сложно приближать разрывы)
2. Квадратичная функция ошибки взлетит очень высоко, что снесет веса и помешает обучению

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/environment.py
> +        if self.with_sprint:
Как-то странно это здесь обрабатывать, нужно просто поле space_dim в BacklogEnv и там уже учитывать

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/environment.py
> +            self.userstory_env.us_td_count
Раз вынесли в класс, можно в классе считать)

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/environment.py
> +        if action < self.userstory_env.us_common_count:
Я сам не догадался, но теперь вижу, получение карточки можно тоже в класс вынести)

2024-02-24 09:21 UTC, krutovsky-danya commented on environment/userstory_env.py
> +def split_cards_in_types(cards: List[Card]):
Такой же метод есть в backlog_env. Хорошо бы вынести в отдельное место)

2024-02-24 09:21 UTC, krutovsky-danya commented on pipeline/logging_study.py
> +            f"\nepisode: {self.episode:03d}\t"
Лучше в конец добавить перенос строки

2024-02-24 15:29 UTC, Cattharine commented on algorithms/deep_q_networks.py
> +            nn.Linear(self.inner_layer, self.inner_layer),
Потому что такая конфигурация была у сеточек (в частности у сеточек, работавших с кредитом), результат которых мы показывали в прошлом семестре. Так как мы переносим результаты исследования прошлого семестра, я посчитала, что это значимо

2024-02-24 15:34 UTC, Cattharine commented on algorithms/deep_q_networks.py
> +                torch.tensor(action, dtype=torch.long),
Версия torch, которая у меня на компьютере, требует для индексации long, boolean или byte

2024-02-24 15:35 UTC, Cattharine commented on environment/backlog_env.py
> +        self.with_sprint = True
Предложения принимаются)
У меня, увы, нет других идей

2024-02-24 15:42 UTC, Cattharine commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
Как раз эта часть добавляет информацию о карточках спринта, если указано желание работать с карточками спринта. Если же такого желания нет, то вектор состояния не добивается нулями; длина вектора состояния меньше

2024-02-24 15:44 UTC, Cattharine commented on environment/credit_payer_env.py
> +        self.with_end = with_end
with_credit_end? Если нет, то предложения принимаются)

2024-02-24 15:50 UTC, Cattharine commented on environment/credit_payer_env.py
> +            return -100
Сейчас действительно не время для этого, так как придется вносить и другие изменения, чтобы функцию награды не перекосило) но, в целом, я это учту

2024-02-24 15:53 UTC, Cattharine commented on environment/environment.py
> +            self.userstory_env.us_td_count
Было сделано по аналогии с backlog environment. Хотя в обоих случаях стоит перекинуть, это в соответствующие классы)

2024-02-24 15:54 UTC, Cattharine commented on environment/environment.py
> +        if action < self.userstory_env.us_common_count:
Это не конечный вариант получения карточки, я почти не переносила изменения в environment. Вроде как ты говорил, что возьмешь environment на себя или я что-то не так поняла?

2024-02-24 15:58 UTC, Cattharine commented on pipeline/logging_study.py
> +            f"\nepisode: {self.episode:03d}\t"
В зависимости от того, как будут выводиться логи, его вообще лучше убрать) что я и сделаю

2024-02-24 16:44 UTC, Cattharine commented on algorithms/deep_q_networks.py
> +            nn.Linear(self.inner_layer, self.inner_layer),
Но это изменение для меня не слишком важно, отстаивать я его не буду)

2024-02-26 17:14 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +            nn.Linear(self.inner_layer, self.inner_layer),
Я тогда зарезовлю обсуждение и создам issue на исследование оптимального размера сети

2024-02-26 17:20 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +                torch.tensor(action, dtype=torch.long),
1. Что такое индексация в нашем случае?
2. Почему на другие вызовы не жалуется?

2024-02-26 17:24 UTC, krutovsky-danya commented on environment/backlog_env.py
> +        self.with_sprint = True
А что значит поле?
Можно что-то такое should_represent_sprint_cards

2024-02-26 17:26 UTC, krutovsky-danya commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
А почему тогда просто не писать `BacklogEnv(x, y, z, 0, 0, 0)`?

2024-02-26 18:37 UTC, Cattharine commented on algorithms/deep_q_networks.py
> +                torch.tensor(action, dtype=torch.long),
1. Индексация тензора, где в качестве "индексов" используются другие тензоры или питоновские списки (или что-то подобное, кортежи вроде тоже подходят). Такая индексация была использована в этой [строчке](https://github.com/Cattharine/product_owner_rl/blob/59df97756780ac63aa06f928b57451e057aab344/algorithms/deep_q_networks.py#L91)
Кстати, о питоновских списках для этого случая. Если в упомянутой мной строчке кастовать actions к питоновскому списку, можно убрать преобразование к long в обсуждаемом изменении. Не уверена, что это лучшая альтернатива, впрочем...
2. В других вызовах используется другой принцип индексации? Например, по обычному числу / питоновскому списку

2024-02-27 12:02 UTC, Cattharine commented on environment/backlog_env.py
> +        self.with_sprint = True
Теперь этого поля нет. Значит, название ему придумывать уже не надо)

2024-02-27 12:10 UTC, Cattharine commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
Мне не нравится идея явного определения BacklogEnv много где. Однако в этом есть свои плюсы, так что пусть будет так, как ты сказал)

2024-02-27 17:00 UTC, krutovsky-danya requested changes

2024-02-27 17:00 UTC, krutovsky-danya commented on environment/credit_payer_env.py
> +        self.with_end = with_end
Можно просто значение передавать типа final_sprint)

2024-02-27 17:00 UTC, krutovsky-danya commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
Зачем нужен этот код, без него будет по-другому?

2024-02-27 17:00 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +                torch.tensor(action, dtype=torch.long),
Понято принято, закрываю тред

2024-02-27 17:12 UTC, Cattharine commented on environment/credit_payer_env.py
> +        self.with_end = with_end
Вот теперь я не понимаю) Где передавать значение?

2024-02-27 17:21 UTC, Cattharine commented on environment/backlog_env.py
> +            assert len(sprint_encoding) == self.sprint_space_dim
Метод _encode_queue начинается с разделения карточек, лежащих в спринте/бэклоге по их типу (обычные, баги, техдолг). После этого из каждой группы выбирается нужное число карточек, которые кодируются. 
Конечно, результат должен быть одинаковым и с этим условием, и без него. Однако при наличии условия мы не будем лишний раз перебирать карточки в спринте

2024-02-29 16:31 UTC, krutovsky-danya requested changes

2024-02-29 16:31 UTC, krutovsky-danya commented on pipeline/base_study.py
> +            done = (t == self.trajectory_max_len)
Теперь не учитывается, что среда вернула done == True
Нужно либо вернуть if, либо обновить формулу

Чем это отличается от предыдущего цикла? Вроде логика не изменилась, просто теперь вручную считаешь действия

2024-02-29 16:56 UTC, Cattharine commented on pipeline/base_study.py
> +            done = (t == self.trajectory_max_len)
С формулой - мой косяк, да. Обновлю

Можно установить trajectory_max_len в отрицательное значение. И это отрицательное значение никогда не будет достигнуто, что равносильно "бесконечной" длине траектории

2024-03-01 03:54 UTC, krutovsky-danya approved these changes

2024-03-01 09:24 UTC, merged