Logging agent steps
Cattharine/product_owner_rl pull request #35
Opened 2024-03-10 10:51 UTC by krutovsky-danya

- add brief description of agent steps

2024-03-10 16:09 UTC, Cattharine requested changes

2024-03-10 16:09 UTC, Cattharine commented on pipeline/logging_study.py
> +            message = 'failed to '
Отрицательный ревард может получиться не только при попытке выполнения недопустимого действия
Например, если в некоторой степени учитывать разность денег при выполнении агентом покупок, можно получить отрицательный ревард
Или при работе со спринтовыми карточками ревард тоже отрицательный

2024-03-10 16:09 UTC, Cattharine commented on pipeline/logging_study.py
> +            message += f'decompose {cards_count} cards'
У нас же сначала выполняется действие, после чего происходит вызов fit_agent, который вызывает _log_action
Значит, к моменту вызова _log_action `self.env.game.userstories.release` уже, по идее, должен быть пустым

2024-03-10 16:09 UTC, Cattharine commented on pipeline/logging_study.py
> +            message += f'release {released_count} user stories'
То же самое, что и с `self.env.game.userstories.release`: `self.env.game.completed_us` должен к этому моменту уже быть пустым

2024-03-11 16:07 UTC, krutovsky-danya commented on pipeline/logging_study.py
> +            message = 'failed to '
убрал

2024-03-11 16:07 UTC, krutovsky-danya commented on pipeline/logging_study.py
> +            message += f'decompose {cards_count} cards'
перенес в место до применения действия

2024-03-11 16:07 UTC, krutovsky-danya commented on pipeline/logging_study.py
> +            message += f'release {released_count} user stories'
++

2024-03-13 07:02 UTC, Cattharine approved these changes
Теперь все должно быть хорошо

2024-03-13 15:00 UTC, merged