Krutovsky make game object
Cattharine/product_owner_rl pull request #4
Opened 2023-12-05 07:42 UTC by krutovsky-danya

2023-12-05 18:07 UTC, Cattharine requested changes
Возможные циклические импорты в game_global и закомментированная строчка в game

2023-12-05 18:07 UTC, Cattharine commented on game/game_global.py
> +from game.userstory_card.userstory_card_info import UserStoryCardInfo
У меня такое ощущение, что вместе с вот такой строчкой из файлика с UserStoryCardInfo (2 строчка в файле)
`from game import game_global as Global`
получается циклический импорт, что не есть хорошо

2023-12-05 18:07 UTC, Cattharine commented on game/game_global.py
> +from game.userstory_card.userstory_card_info import UserStoryCardInfo
Возможно, стоит разделить этот файл на два: один с GlobalContext, другой - со всем остальным из этого файла?

2023-12-05 18:07 UTC, Cattharine commented on game/game.py
> +            # Global.release_color(us.card_type, us.color)
Почему данная строчка закомментирована? Учитывая, что при создании юзерстори цвет все ещё занимается (файл с UserStoryCardInfo), то это все сломает

2023-12-05 18:45 UTC, Cattharine requested changes
Пара багов в game_global

2023-12-05 18:45 UTC, Cattharine commented on game/game_global.py
> +        self.check_money(self._money)
Метод check_money не принимает никакие аргументы на вход

2023-12-05 18:45 UTC, Cattharine commented on game/game_global.py
> +        self.check_money(self._money)
`        self._money -= NEW_ROOM_COST * self.current_room_multiplier`

`        self.check_money()`

2023-12-06 11:43 UTC, krutovsky-danya commented on game/game_global.py
> +from game.userstory_card.userstory_card_info import UserStoryCardInfo
++

2023-12-06 11:43 UTC, krutovsky-danya commented on game/game.py
> +            # Global.release_color(us.card_type, us.color)
++

2023-12-06 12:09 UTC, krutovsky-danya commented on game/game_global.py
> +        self.check_money(self._money)
++
Еще простеньким тестом покрыл

2023-12-06 12:09 UTC, krutovsky-danya commented on game/game_global.py
> +        self.check_money(self._money)
Кстати, текущие тесты не проверяли этого

2023-12-06 12:10 UTC, krutovsky-danya commented on game/game_global.py
> +        self.check_money(self._money)
++

2023-12-06 12:10 UTC, krutovsky-danya commented on game/game_global.py
> +        self.check_money(self._money)
++

2023-12-09 00:19 UTC, Cattharine reviewed
2 опечатки и 2 комментария к инициализации информации о карточках. В остальном хорошо

2023-12-09 00:19 UTC, Cattharine commented on game/userstory_card/bug_user_story_info.py
> +        super().__init__(label_val="Bug", spawn_sprint=spawn_sprint)
Если UserStoryCardInfo требует при инициализации ColorStorage, то мы должны требовать эту информацию при инициализации и здесь

2023-12-09 00:19 UTC, Cattharine commented on game/userstory_card/tech_debt_user_story_info.py
> +        super().__init__(label_val="TechDebt", spawn_sprint=spawn_sprint)
Если UserStoryCardInfo требует при инициализации ColorStorage, то мы должны требовать эту информацию при инициализации и здесь

2023-12-09 00:19 UTC, Cattharine commented on game/userstory_card/userstory_card_info.py
> +        user_stroy_customers = GlobalConstants.USERSTORY_CUSTOMER
Опечатка: должно быть "story", а не stroy

2023-12-09 00:22 UTC, Cattharine commented on game/game_global.py
> +        self.check_money(self._money)
Да, они проверяют недоступность покупки роботов / комнат при начале игры

2023-12-09 00:25 UTC, Cattharine reviewed
1 комментарий

2023-12-09 00:25 UTC, Cattharine commented on game/game_variables.py
> +        self.check_money(self._money)
Здесь передаем check_money информацию, которую метод не принимает

2023-12-09 10:19 UTC, krutovsky-danya commented on game/game_global.py
> +        self.check_money(self._money)
Поправил все использования check_money

2023-12-10 22:32 UTC, Cattharine reviewed
Мы обсуждали про типизацию. Хотя в прошлый раз я это нигде не указала, да

2023-12-10 22:32 UTC, Cattharine commented on game/game.py
> +        self.cards_in_sprint: list[CardInfo] = []
Типизация

2023-12-10 22:32 UTC, Cattharine commented on game/userstory_card/userstory_card_info.py
> +        self.related_cards: list[CardInfo] = []
Типизация

2023-12-10 22:32 UTC, Cattharine commented on game/game.py
> +    def _update_tech_debt_impact_stories(self, stories: dict[int, UserStoryCardInfo], full_tech_debt_debuff: int):
Типизация

2023-12-10 22:32 UTC, Cattharine commented on game/game_constants.py
> +    statistical_research_cost = 80000
statistical_research_cost объявлен второй раз (первый раз был в 9 строке)

2023-12-11 04:38 UTC, Cattharine approved these changes
Все чудесно

2023-12-11 04:54 UTC, merged