Аctions availability
Cattharine/product_owner_rl pull request #40
Opened 2024-03-25 14:51 UTC by Cattharine

Make agent use info of actions availability

2024-03-26 06:06 UTC, krutovsky-danya requested changes
Проверил локально, очень круто стало обучаться. Ты молодец!

2024-03-26 06:06 UTC, krutovsky-danya commented on algorithms/deep_q_networks.py
> +        masked_action = np.random.choice(np.arange(len(mask)), p=probs)
Скорее докапываюсь: можно вместо `np.arange(len(mask))` сразу `mask` подавать

Тогда буем меньше памяти аллоцировать, значит чуть быстрее работать

2024-03-26 06:06 UTC, krutovsky-danya commented on pipeline/base_study.py
> +        info = init_info
А почему не `info = self.env.get_info()`

`init_state` было вынесено, чтобы считать оценку начального состояния, а начальное info вроде не особо нужно

2024-03-26 06:33 UTC, krutovsky-danya commented on final_sprints_main.py
> +    env = ProductOwnerEnv(with_info)
Тут кажется with_info=with_info

2024-03-26 21:01 UTC, Cattharine commented on pipeline/base_study.py
> +        info = init_info
Можно, конечно, и `info = self.env.get_info()`

Но в моей голове state и info довольно сильно связаны и мне захотелось для них единообразия)

2024-03-27 04:33 UTC, krutovsky-danya approved these changes

2024-03-27 10:23 UTC, merged