Reward system update
Cattharine/product_owner_rl pull request #43
Opened 2024-04-19 16:39 UTC by Cattharine

- Updated reward system. Now it does not depend on state vector
- Added new reward system

2024-04-21 06:50 UTC, krutovsky-danya requested changes
Много докопался по стилю, по логике замечаний почти нет)

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/empirical_reward_system.py
> -        if (state_old == state_new).all():
Со словарями равенство в питоне хорошо работает, поэтому можно оставить этот if и не передавать значение success (мне кажется это костыль)

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/base_reward_system.py
> +    def copy_state(self, game: ProductOwnerGame):
Хорошая идея, но реализация не должна лежать в reward_system, можно положить ее отдельно. Например рядом с environment

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/environment.py
> +        done = self.game.context.done or len(info) == 0 or (self.game.context.customers <= 0 and not self.game.context.is_new_game)
Очень много логики в одной строчке, давай вынесем в отдельный метод, который можно разбить на несколько строк)

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        first = self.get_first_sum_part(state_new) - self.get_first_sum_part(state_old)
Названия first, second и так далее ничего не говорят о смысле переменной, нужно переименовать
Почему-то же ты разделила методы

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        return max((7 - blank_sprint_counter) * customers * loyalty, 0) * self.potential_weight
`customers * loyalty * self.potential_weight` - это, видимо, доход за пустой спринт, можно назвать `income` 
А остальной множитель - количество таких спринтов, поэтому назвал бы такой метод get_free_income

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        reward = first + second + third + fourth
В телеге было написано, что считается разница потенциальных доходов, можно сумму слагаемых и дописать как potential_income и брать разницу значений нового состояния и старого

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        if blank_counter - 4 < 9:
Как будто нужно инвертировать if + после return else не нужен

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +            sums = (3 + indexes) / 2 * (indexes - 2) / 3
Непонятно, что такое sums по смыслу кажется, что это убывание величин, а не суммы

2024-04-21 06:50 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        n = (2 * customers - 11) // 3
Магические константы хотелось бы назвать, если есть возможность. Если они например что-то значат, например, 11 точно откуда-то взялось, не из кода игры

2024-04-21 12:36 UTC, Cattharine commented on environment/reward_sytem/empirical_reward_system.py
> -        if (state_old == state_new).all():
Можно ли гарантировать, что равенство со словарями всегда будет соответствовать успеху действия? Даже если мы поменяем наполнение словаря когда-нибудь потом?

2024-04-21 12:42 UTC, Cattharine commented on environment/reward_sytem/base_reward_system.py
> +    def copy_state(self, game: ProductOwnerGame):
Мне кажется, что удобно её расположить именно рядом с reward_system, чтобы знать, какая информация reward_system требуется для работы и как именно её получили

2024-04-21 12:51 UTC, Cattharine commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        if blank_counter - 4 < 9:
Как инвертировать? blank_counter - 4 >=9 и действие под if то же? Нет, так как в этой части считается сумма от 7 до 13 пустого спринта

2024-04-21 12:54 UTC, Cattharine commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +            sums = (3 + indexes) / 2 * (indexes - 2) / 3
Да, здесь нужен комментарий. Без деления на 3 это сумма арифметической прогрессии для каждого элемента indexes от 3 до элемента indexes включительно

2024-04-21 12:59 UTC, Cattharine commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        n = (2 * customers - 11) // 3
Тут скорее нужен комментарий, что переменная n является минимальным целым решением неравенства, числом шагов, за которое количество пользователей упадет ниже 0

2024-04-21 16:16 UTC, krutovsky-danya requested changes

2024-04-21 16:16 UTC, krutovsky-danya commented on environment/reward_sytem/empirical_reward_system.py
> -        if (state_old == state_new).all():
Точнее говоря, равенство соответствует неуспеху
Потом в плане кода? Ну у нас равные состояния должны соответствовать одинаковым играм

2024-04-21 16:16 UTC, krutovsky-danya commented on environment/reward_sytem/base_reward_system.py
> +    def copy_state(self, game: ProductOwnerGame):
Может по хорошему вообще игру научиться копировать?
Ну если рядом с reward_system, то точно не в самом классе, пожалуйста

2024-04-21 16:16 UTC, krutovsky-danya commented on environment/reward_sytem/full_potential_credit_reward_system.py
> +        if blank_counter - 4 < 9:
Ну инвертировать условие ифа и тело else переставить 
```
if blank_counter - 4 >= 9:
  return 0
indexes = ...```

2024-04-21 16:35 UTC, Cattharine commented on environment/reward_sytem/empirical_reward_system.py
> -        if (state_old == state_new).all():
Да, точно)
Но ведь словарь не полностью соответствует вектору состояния... 
К тому же я не считаю передачу success костылем. У нас есть прямой признак того, было действие совершено или нет. Почему бы его не использовать в системе наград вместо того, чтобы оценивать это по косвенным признакам?

2024-04-21 16:43 UTC, Cattharine commented on environment/reward_sytem/base_reward_system.py
> +    def copy_state(self, game: ProductOwnerGame):
Думала над этим. Не хотелось бы копировать игру...
Тогда предлагаю так: создать ещё один класс, назвать его reward_adapter, перенести в него всю логику со словарем, унаследовать base_reward_system от reward_adapter. В таком случае системы наград задаются, начиная с base_reward_system, и всем системам наград будет доступна информация из адаптера

2024-04-27 06:17 UTC, krutovsky-danya approved these changes

2024-05-02 11:29 UTC, merged