Parse game user strories and backlog
Cattharine/product_owner_rl pull request #44
Opened 2024-04-27 06:02 UTC by krutovsky-danya

User strories description and backlog is a crucial part of the game.
This PR implements reading data from screenshot

2024-05-02 12:33 UTC, Cattharine requested changes
Хотелось бы переименовать директорию tests: добавить информацию о том, что это тесты, связанные с парсингом изображений
Смущает большое количество констант в web_interaction/image_parser (особенно в слайсах списков), но не уверена, что именно с этим следует делать

2024-05-02 12:33 UTC, Cattharine commented on web_interaction/image_parser.py
> +    return color, loyalty_value, customers_value
Судя по тестам из tests/test_image_parsing, у меня возникает ощущение, что `color[0, 0]` - белый пиксель. Раз он есть в описании карточки, то скорее всего предполагался цвет карточки. Если это так, то цвет карточки определяется неверно

2024-05-02 12:33 UTC, Cattharine commented on web_interaction/image_parser.py
> +    return color, hours_value
То же самое, что и для юзерстори карточек. Скорее всего цвет карточки неверно определяется как белый

2024-05-02 12:33 UTC, Cattharine commented on tests/test_image_parsing.py
> +        assert hours == expected_hours
Карточки на картинке - желтые, здесь ожидаемый цвет указан как белый. Цвет карточек определяется неправильно

2024-05-02 12:33 UTC, Cattharine commented on tests/test_image_parsing.py
> +        assert customers == ex_customers
Цвет карточек на картинке не белый

2024-05-03 14:21 UTC, krutovsky-danya reviewed
С константами пока правда не знаю, что делать, если делать пропорционально экрану все шаблоны поедут. Накручивать распознавание символов сейчас тяжело.
Можешь попробовать у себя запустить ipynb файл, и сказать, какой у тебя размер ifram-a?
Если такой же, то не страшно, что константы)

2024-05-03 14:21 UTC, krutovsky-danya commented on web_interaction/image_parser.py
> +    return color, loyalty_value, customers_value
Да, правда, спасибо, что заметила!

2024-05-12 23:02 UTC, Cattharine commented
> Можешь попробовать у себя запустить ipynb файл, и сказать, какой у тебя размер ifram-a?

Под "у себя" подразумевается в colab или у себя на компьютере?
В colab'е такой же, height=540, width=960
Локально другой: height=1038, width=1920

2024-05-12 23:14 UTC, Cattharine approved these changes

2024-05-16 10:59 UTC, merged