Add initial environment version
Cattharine/product_owner_rl pull request #5
Opened 2023-12-06 01:14 UTC by Cattharine

Добавлена обертка игры в стиле rl / gym

2023-12-06 06:54 UTC, krutovsky-danya requested changes

2023-12-06 06:54 UTC, krutovsky-danya commented on environment/environment.py
> +        return self._get_cards_descriptions(4, 2, 1, False,
Почему здесь 4, 2. 1, False? От чего это зависит?

2023-12-06 06:54 UTC, krutovsky-danya commented on environment/environment.py
> +        self._perform_action(action)
Кажется _perform_action и должен возвращать награду
Стоит наказывать за неправильные действия, например, за выпуск пустого релиза (когда нечего релизить) или покупку комнаты сверх меры и так далее

2023-12-06 06:54 UTC, krutovsky-danya commented on environment/environment.py
> +    def _get_reward(self):
Тут еще нет учета, что игра закончилась, думаю логично накидывать награды, за победу и штраф, за проигрыш

2023-12-06 06:54 UTC, krutovsky-danya commented on game/game.py
> +# class ProductOwnerGame:
Вроде этот код не мешался (да, сорри, случайно пушнул в main), а эти изменения создадут конфликты с моим PR

2023-12-06 06:54 UTC, krutovsky-danya commented on game/game.py
> +def move_userstory_card(card):  # !
Не осознал изменения, зачем это?

2023-12-06 08:58 UTC, Cattharine commented on environment/environment.py
> +        return self._get_cards_descriptions(4, 2, 1, False,
Зависит от количества фичей в описании карточки (например, у обычной юзерстори их 4, у юзерстори бага 2, у юзерстори тех долга 1). 
Используется, чтобы сохранять формат списка фичей.

2023-12-06 09:03 UTC, Cattharine commented on game/game.py
> +def move_userstory_card(card):  # !
Чтобы по юзерстори/бэклогу не искать индекс карточки, так как это бесполезная трата времени, если мы уже храним карточку, с которой будем работать. Решила оставить оба варианта: и с индексом, и с самой карточкой

2023-12-06 12:18 UTC, krutovsky-danya commented on environment/environment.py
> +        return self._get_cards_descriptions(4, 2, 1, False,
То есть нужно переделать на какие-то поля самого класса? А то будем менять параметры, а ничего не изменится

2023-12-06 12:19 UTC, krutovsky-danya commented on game/game.py
> +def move_userstory_card(card):  # !
Может просто вспомогательный метод написать?

2023-12-11 17:37 UTC, Cattharine commented on environment/environment.py
> +        return self._get_cards_descriptions(4, 2, 1, False,
Пришли к соглашению, что вынесем эти чиселки в константы.

2023-12-11 17:41 UTC, Cattharine commented on environment/environment.py
> +        self._perform_action(action)
Кажется, пришли к соглашению, что пока оставим -1 за каждый ход. Чем больше неправильных действий совершит, тем больше будет наказание

2023-12-11 18:00 UTC, Cattharine commented on game/game.py
> +# class ProductOwnerGame:
Померджила изменения из main, так что конфликта не будет

2023-12-11 18:02 UTC, Cattharine commented on environment/environment.py
> +    def _get_reward(self):
Добавила. Размер награды в обоих случаях можно обсудить

2023-12-11 18:46 UTC, Cattharine commented on game/game.py
> +def move_userstory_card(card):  # !
Вероятно, я не совсем понимаю, что ты хочешь вынести во вспомогательный метод, но все варианты, которые мне приходят в голову, меня не устраивают.
Я была бы не против перегрузить этот метод, но, увы, у меня эта фича не работает

2023-12-12 05:38 UTC, krutovsky-danya commented on game/game.py
> +def move_userstory_card(card):  # !
Я имел в виду метод отдельный def move_backlog_card_by_index(self, card_index) или что-то в этом духе)

2023-12-12 05:41 UTC, krutovsky-danya approved these changes

2023-12-12 05:52 UTC, merged