Add soft actor critic
Cattharine/product_owner_rl pull request #64
Opened 2024-10-26 22:07 UTC by Cattharine

Added Soft Actor Critic Discrete with guides. There are two implementations: with and without learning temperature

2024-10-27 09:47 UTC, krutovsky-danya requested changes
Очень хорошо, что PR сконцентрирован только на алгоритме!

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +    def predict(self, state):
Тут не нужент torch.no_grad?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        logits[~guide] = -torch.inf
Почему для однообразия не использовать masked_fill?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        np_probs = np.asarray(masked_probs).astype("float64")
А ошибка все еще сохранилась?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        next_guides = next_guides.to(self.device)
Давай вынесем эту логику в отдельный метод? Кажется этот код немного мешает пониманию происходящего в fit

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        entropy = self.alpha.detach() * next_action_log_probs
Кажется это только часть энтропии, чтобы не путаться я бы предложил назвать переменную по-другому или честно посчитать энтропию

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        next_action_log_probs = get_nan_safe_log(next_action_probs, self.small_const)
Можно получить log_probs отнормировав логиты (logits - torch.logsumexp(logits))

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        q_value_1 = self.q_function_1.forward(states).detach()
Нормально ли то, что значения Q функций вычисляется после их градиентного шага?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        entropy = self.alpha.detach() * action_log_probs
Почему бы не вынести это в отдельную функцию?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        loss_policy = torch.mean(torch.sum(action_probs * (entropy - min_q_value), dim=1))
Кажется все это было уже вычислено в методе выше (только с другим знаком), разве нет?

2024-10-27 09:47 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        loss_alpha = torch.sum(action_probs *
Кажется это совпадает полностью с policy_loss, на самом деле даже код особо не нужно менять, просто шагнуть еще по alpha тоже

2024-10-27 13:19 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +    def predict(self, state):
Не думаю. Для меня forward и predict различаются тем, что в forward я могу передать много состояний, а в predict - только одно. Это различие не предполагает отсутствие градиента в predict

2024-10-27 13:21 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        logits[~guide] = -torch.inf
Тогда уж masked_fill_ (inplace версию masked_fill), так как out-of-place операции копируют тензор, из-за чего тратят больше памяти. Но по сути там уже и так использован masked_fill_, просто запись другая

2024-10-27 13:25 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        np_probs = np.asarray(masked_probs).astype("float64")
Увы, да. Судя по всему, np.choice неявно внутри приводит тип к float64, а masked_probs хранит элементы типа float32 (по крайней мере, у меня отрабатывает так), и из-за этого вероятности не суммируются к единице

2024-10-27 14:05 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        next_action_log_probs = get_nan_safe_log(next_action_probs, self.small_const)
Будет ли это работать с учетом масок и -torch.inf?

2024-10-27 14:09 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        q_value_1 = self.q_function_1.forward(states).detach()
Думаю, это нормально. К тому же, так же сделано и в реализации, ссылку на репозиторий с которой я оставила в issue для sac

2024-10-27 14:11 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        loss_policy = torch.mean(torch.sum(action_probs * (entropy - min_q_value), dim=1))
Нет. В loss для q функций это считается для следующих состояний, в loss для policy это считается для текущих состояний

2024-10-27 14:13 UTC, Cattharine commented on algorithms/soft_actor_critic.py
> +        loss_alpha = torch.sum(action_probs *
К сожалению, они не совпадают. В policy_loss ещё учитывается min_q_value, а в alpha_loss учитывается target_entropy

2024-10-27 15:07 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        next_action_log_probs = get_nan_safe_log(next_action_probs, self.small_const)
Да, это точно работает с -torch.inf

2024-10-27 15:08 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        q_value_1 = self.q_function_1.forward(states).detach()
Ух, что-то мне от этого странно, но давай пока так попробуем

2024-10-27 15:14 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        q_value_1 = self.q_function_1.forward(states).detach()
Кажется там в репозитории активные дискуссии. Давай я заведу issue на эту тему у нас, чтобы поисследовать. Если станет лучше и стабильнее в том репозитории расскажем)

2024-10-30 14:51 UTC, krutovsky-danya approved these changes

2024-10-30 14:54 UTC, krutovsky-danya commented on algorithms/soft_actor_critic.py
> +        log_probs = log_probs.masked_fill(~guides, 0.0)
Тут же не ноль, а -inf. Потому что логарифм нуля - это -inf

2024-10-30 15:54 UTC, merged